name: Mirror Python Standalone Release

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: '0 3 * * *' # Run daily at 3 AM UTC

permissions:
  contents: read    # To checkout the repository
  packages: write   # To push Docker image to GHCR

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python version for the script

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download latest Python release
        run: python download_release.py

      - name: Read Python version
        id: read_version
        run: echo "version=$(cat artifact/version.txt)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/python-standalone-mirror:${{ steps.read_version.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/python-standalone-mirror:latest
          build-args: |
            PYTHON_VERSION=${{ steps.read_version.outputs.version }}
          platforms: linux/amd64 # Explicitly build for x86-64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Print image digest
        run: echo "Pushed image with digest: ${{ steps.build-and-push.outputs.digest }}"

